apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: orec2zijo-go
  janus-idp.io/tekton: orec2zijo-go
  backstage.io/kubernetes-id: orec2zijo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: orec2zijo-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
