apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: orec2zijo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: orec2zijo-go 
  name: orec2zijo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: orec2zijo-go 
